apiVersion: v1
kind: Service
metadata:
  name: demo-fastapi-service
spec:
  type: NodePort
  selector:
    app: demo-fastapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
