apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nextjs-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-nextjs-app
  template:
    metadata:
      labels:
        app: demo-nextjs-app
    spec:
      containers:
      - name: demo-nextjs-app
        image: yukikitayama/demo-nextjs-app
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "100m"
            memory: "500Mi"
            ephemeral-storage: "100Mi"
          requests:
            cpu: "100m"
            memory: "500Mi"
            ephemeral-storage: "100Mi"