apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nextjs-app-deployment
spec:
  selector:
    matchLabels:
      app: demo-nextjs-app
  template:
    metadata:
      labels:
        app: demo-nextjs-app
    spec:
      containers:
      - name: demo-nextjs-app
        image: yukikitayama/demo-nextjs-app
        ports:
        - containerPort: 3000